[profile.default]
src = 'contracts'
out = 'out'
script = 'scripts'
libs = ['lib', 'node_modules']
solc_version = "0.8.19"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20_000


[profile.ci]
verbosity = 4

[profile.ci.fuzz]
runs = 10

[rpc_endpoints]
fantom-testnet = "https://rpc.ankr.com/fantom_testnet"

[etherscan]
fantom-testnet = { key = "${FMT_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
