name: prettier & linters

on:
    push:
        branches:
            - dev
    pull_request: {}

jobs:
    prettier:
        name: Prettier check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actionsx/prettier@v2
              with:
                  args: --check .
